### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by AmitMY** [mark-borg/sign-language-detection#1]
Hi Mark, cool work,
I was wondering about inference speed of this method - for every timestamp (at 5hz), how long does it take to determine signing / not signing?

**Comment by mark-borg** [comment]
Hello, thanks.
On my machine (with an old GPU now), each video frame takes between 0.4 to
0.5 seconds.
Roughly 80% of the time consists of CNN feature extraction (via the
VGG-16). The RNNs are quite fast.
I have not yet been able to test with a faster GPU.

**Comment by AmitMY** [comment]
Thanks, Mark,
do you have numbers on CPU by any chance?

Using this repo - https://github.com/jcjohnson/cnn-benchmarks - as a guide, I don't want to assume, but roughly 3 seconds

**Comment by mark-borg** [comment]
No, haven't tried on just a CPU, but the estimate of 3 seconds sounds
reasonable.
When I have time, I also want to try with different, faster CNNs.

**Comment by AmitMY** [comment]
Thanks, Mark, that's very helpful.
I'm working on the same task - SL Detection - and at 20ms-50ms processing per frame on CPU get 90% accuracy.
I can share it with you, if you'd like, via email, because it wasn't yet peer-reviewed.
(I couldn't find your email address)

**Comment by mark-borg** [comment]
Yes, that would be great. My email is mborg2005 <at> gmail <dot> com.
Thanks.
